# Generated by Django 4.0.6 on 2022-07-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_id_transaction_credit_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='debit',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
