# Generated by Django 4.0.6 on 2022-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_in',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_out',
            field=models.DateField(null=True),
        ),
    ]
